# Generated by Django 3.0.8 on 2020-07-23 20:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200723_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='profile_pic'),
            preserve_default=False,
        ),
    ]
