# Generated by Django 3.0.8 on 2020-07-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_name',
            field=models.CharField(default='user_name', max_length=10, unique=True),
        ),
    ]
